## Identidy spikes - case 1: non-reasoning models

In [3]:
import pandas as pd, numpy as np
from pathlib import Path

path = "/Data/allegra-maria-pia.boustany/llm_cross_eval/results/exp1_turn1_Qwen2_5-1_5B-Instruct_vs_Qwen2_5-7B-Instruct_1768314942.csv"
df = pd.read_csv(path)

df["log_ratio"] = np.log(df["ratio_pA_over_pB"].clip(lower=1e-12))
df["abs_log_ratio"] = df["log_ratio"].abs()

In [4]:
top = (df.sort_values("abs_log_ratio", ascending=False)
         .groupby(["example_id"])
         .head(30))
top[["example_id","token_idx","token_str","p_a","p_b","ratio_pA_over_pB","log_ratio"]].head(30)

,example_id,token_idx,token_str,p_a,p_b,ratio_pA_over_pB,log_ratio
1950,2,568,remainder,0.964041,0.000017,57721.148256,10.963379
345,0,345,5,0.558762,0.000066,8458.852034,9.042969
536,0,536,2,0.672681,0.000180,3746.268755,8.228516
1047,1,325,).,0.684610,0.000203,3364.698873,8.121094
561,0,561,range,0.123224,0.000051,2395.267034,7.781250
1943,2,561,Finally,0.428418,0.000335,1277.095643,7.152344
1283,1,561,frac,0.095967,0.000140,686.255495,6.531250
1573,2,191,)^,0.267052,0.000431,619.980174,6.429688
763,1,41,divides,0.097478,0.000180,542.872779,6.296875
501,0,501,m,0.725922,0.001600,453.587185,6.117188
1585,2,203,chocolate,0.256821,0.000688,373.110641,5.921875
1948,2,566,find,0.965690,0.003721,259.521069,5.558838
964,1,242,EF,0.345591,0.001412,244.691932,5.500000
132,0,132,there,0.061000,0.000261,233.486673,5.453125
1550,2,168,chocolate,0.293299,0.001813,161.731491,5.085938
493,0,493,restriction,0.053833,0.000380,141.616826,4.953125
503,0,503,cannot,0.041275,0.000296,139.421260,4.937500
192,0,192,(k,0.105399,0.000912,115.584285,4.750000
1033,1,311,:,0.348301,0.003284,106.066102,4.664062
289,0,289,any,0.048255,0.000520,92.874582,4.531250
281,0,281,2,0.040635,0.000553,73.469841,4.296875
380,0,380,Similarly,0.074739,0.001066,70.105412,4.250000
1122,1,400,.\n,0.029268,0.000504,58.119428,4.062500
599,0,599,include,0.135335,0.002329,58.119428,4.062500
1097,1,375,\),0.753367,0.014264,52.815086,3.966797
238,0,238,always,0.060055,0.001171,51.290215,3.937500
1519,2,137,\,0.775765,0.015666,49.518372,3.902344
1399,2,17,3,0.060055,0.001327,45.263456,3.812500
523,0,523,).,0.721681,0.017206,41.943695,3.736328
1031,1,309,two,0.342901,0.009210,37.232703,3.617188

In [5]:
def show_spike_context(df, example_id, token_idx, window=10):
    g = df[(df.example_id==example_id)].sort_values("token_idx")
    lo, hi = token_idx - window, token_idx + window
    ctx = g[(g.token_idx >= lo) & (g.token_idx <= hi)].copy()
    ctx["mark"] = np.where(ctx.token_idx==token_idx, "<<<SPIKE<<<", "")
    return ctx[["token_idx","token_str","ratio_pA_over_pB","log_ratio","mark"]]

# Show top 5 spikes with context
for i in range(30):
    row = top.iloc[i]
    print(f"\nSpike {i}: example_id={row.example_id}, token_idx={row.token_idx}, abs_log_ratio={row.abs_log_ratio:.3f}")
    display(show_spike_context(df, row.example_id, row.token_idx, window=12))

Spike 0: example_id=2, token_idx=568, abs_log_ratio=10.963

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1938        556                      0.999998 -2.026558e-06
1939        557           2          0.999801 -1.986027e-04
1940        558           5          1.000008  8.463860e-06
1941        559           \          0.999888 -1.116991e-04
1942        560       ]\n\n          0.994759 -5.254745e-03
1943        561     Finally       1277.095643  7.152344e+00
1944        562           ,          1.000000 -3.576279e-07
1945        563          we          0.944977 -5.659485e-02
1946        564        need          0.977700 -2.255249e-02
1947        565          to          0.932733 -6.963634e-02
1948        566        find        259.521069  5.558838e+00
1949        567         the          1.005938  5.920410e-03
1950        568   remainder      57721.148256  1.096338e+01  <<<SPIKE<<<
1951        569        when          0.972077 -2.832031e-02
1952        570                      1.920036  6.523438e-01
1953        571           2          1.000093  9.286404e-05
1954        572           5          0.999997 -3.218651e-06
1955        573          is          0.999968 -3.242493e-05
1956        574     divided          0.999998 -2.384186e-06
1957        575          by          1.000000  0.000000e+00
1958        576                      0.999981 -1.871586e-05
1959        577           1          0.999996 -4.053116e-06
1960        578           0          1.000057  5.674362e-05
1961        579           0          0.999918 -8.165836e-05
1962        580           0          0.999961 -3.886223e-05

Spike 1: example_id=0, token_idx=345, abs_log_ratio=9.043

     token_idx token_str  ratio_pA_over_pB  log_ratio         mark
333        333                    0.999973  -0.000027
334        334         2          0.999024  -0.000976
335        335         5          0.999560  -0.000440
336        336         9          0.999370  -0.000630
337        337        \n          1.000977   0.000977
338        338         \          0.999991  -0.000009
339        339       ]\n          0.999980  -0.000020
340        340       and          1.366838   0.312500
341        341        \n          0.891232  -0.115150
342        342         \          0.999986  -0.000014
343        343       [\n          1.000004   0.000004
344        344         2          0.686199  -0.376587
345        345         5       8458.852034   9.042969  <<<SPIKE<<<
346        346         9          0.992921  -0.007104
347        347         =          3.426178   1.231445
348        348                    0.985218  -0.014893
349        349         2          1.234835   0.210937
350        350         8          0.948632  -0.052734
351        351         \          2.943472   1.079590
352        352      cdot          0.989602  -0.010452
353        353                    0.878414  -0.129637
354        354         9          0.991370  -0.008667
355        355         +          0.787674  -0.238670
356        356                    0.999144  -0.000857
357        357         7          0.951212  -0.050018

Spike 2: example_id=0, token_idx=536, abs_log_ratio=8.229

     token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
524        524   Therefore          1.310630  2.705078e-01
525        525           ,          1.000000 -1.192093e-07
526        526          \(          3.253357  1.179688e+00
527        527           m          1.034897  3.430176e-02
528        528          \)          1.057468  5.587769e-02
529        529         can          1.077963  7.507324e-02
530        530        take         27.028044  3.296875e+00
531        531         any          1.629513  4.882812e-01
532        532     integer          0.983295 -1.684570e-02
533        533       value          0.930397 -7.214355e-02
534        534        from          1.634294  4.912109e-01
535        535                      0.999460 -5.400181e-04
536        536           2       3746.268755  8.228516e+00  <<<SPIKE<<<
537        537          to          1.895583  6.395264e-01
538        538    infinity          1.243305  2.177734e-01
539        539           .          1.317045  2.753906e-01
540        540     However          0.344243 -1.066406e+00
541        541           ,          1.000000  0.000000e+00
542        542          we          0.604166 -5.039062e-01
543        543         are          1.489496  3.984375e-01
544        544       asked          1.404728  3.398437e-01
545        545          to          0.821574 -1.965332e-01
546        546        find          0.999512 -4.882812e-04
547        547         the          1.007374  7.347107e-03
548        548         sum          1.006846  6.822586e-03

Spike 3: example_id=1, token_idx=325, abs_log_ratio=8.121

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1035        313          (\          1.000000 -2.384186e-07
1036        314    triangle          0.999922 -7.772446e-05
1037        315           A          0.627007 -4.667969e-01
1038        316          FE          0.692680 -3.671875e-01
1039        317          \)          0.994317 -5.699158e-03
1040        318         and          0.998491 -1.509666e-03
1041        319           \          0.960459 -4.034424e-02
1042        320          (\          0.999998 -1.907349e-06
1043        321    triangle          0.999938 -6.246567e-05
1044        322           B          2.436652  8.906250e-01
1045        323          EM         34.704696  3.546875e+00
1046        324           \          2.091315  7.377930e-01
1047        325          ).       3364.698873  8.121094e+00  <<<SPIKE<<<
1048        326          We          1.548830  4.375000e-01
1049        327        need          4.017360  1.390625e+00
1050        328          to          1.010646  1.058960e-02
1051        329        find          1.003424  3.417969e-03
1052        330         the          1.006944  6.919861e-03
1053        331       areas          0.984496 -1.562500e-02
1054        332          of          0.999946 -5.364418e-05
1055        333       these          0.939356 -6.256104e-02
1056        334   triangles          0.874668 -1.339111e-01
1057        335         and          0.520569 -6.528320e-01
1058        336        then          7.698424  2.041016e+00
1059        337         sum          8.655571  2.158203e+00

Spike 4: example_id=0, token_idx=561, abs_log_ratio=7.781

     token_idx  token_str  ratio_pA_over_pB  log_ratio         mark
549        549         of          0.999996  -0.000004
550        550        all          1.001454   0.001453
551        551       such          1.604250   0.472656
552        552   integers          7.865609   2.062500
553        553         \(          0.742049  -0.298340
554        554          b          0.950516  -0.050751
555        555          \          1.426849   0.355469
556        556         ),          1.591765   0.464844
557        557         so         27.453674   3.312500
558        558         we          0.900892  -0.104370
559        559   consider          0.698113  -0.359375
560        560        the          0.886167  -0.120850
561        561      range       2395.267034   7.781250  <<<SPIKE<<<
562        562   starting          1.927550   0.656250
563        563       from          1.004249   0.004240
564        564                     1.789670   0.582031
565        565          2          0.673256  -0.395630
566        566          8          0.915246  -0.088562
567        567         up          2.020056   0.703125
568        568         to          1.000627   0.000627
569        569   infinity          2.916291   1.070312
570        570          .          1.155498   0.144531
571        571        But          2.253535   0.812500
572        572      since          1.340401   0.292969
573        573        the          1.094003   0.089844

Spike 5: example_id=2, token_idx=561, abs_log_ratio=7.152

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1931        549           5          1.000304  3.037453e-04
1932        550           5          1.000057  5.698204e-05
1933        551           -          1.000010  1.025200e-05
1934        552                      0.999644 -3.557205e-04
1935        553           3          0.997748 -2.254486e-03
1936        554           0          0.997645 -2.357483e-03
1937        555           =          1.000104  1.039505e-04
1938        556                      0.999998 -2.026558e-06
1939        557           2          0.999801 -1.986027e-04
1940        558           5          1.000008  8.463860e-06
1941        559           \          0.999888 -1.116991e-04
1942        560       ]\n\n          0.994759 -5.254745e-03
1943        561     Finally       1277.095643  7.152344e+00  <<<SPIKE<<<
1944        562           ,          1.000000 -3.576279e-07
1945        563          we          0.944977 -5.659485e-02
1946        564        need          0.977700 -2.255249e-02
1947        565          to          0.932733 -6.963634e-02
1948        566        find        259.521069  5.558838e+00
1949        567         the          1.005938  5.920410e-03
1950        568   remainder      57721.148256  1.096338e+01
1951        569        when          0.972077 -2.832031e-02
1952        570                      1.920036  6.523438e-01
1953        571           2          1.000093  9.286404e-05
1954        572           5          0.999997 -3.218651e-06
1955        573          is          0.999968 -3.242493e-05

Spike 6: example_id=1, token_idx=561, abs_log_ratio=6.531

      token_idx token_str  ratio_pA_over_pB     log_ratio         mark
1271        549         \          1.005061  5.047798e-03
1272        550      text          1.000018  1.752377e-05
1273        551         {          0.999999 -8.344650e-07
1274        552      Area          1.000026  2.574921e-05
1275        553        of          0.999989 -1.096725e-05
1276        554         }          1.005054  5.041122e-03
1277        555         \          1.006688  6.666183e-03
1278        556  triangle          1.001904  1.902580e-03
1279        557         B          0.998460 -1.541138e-03
1280        558        EM          0.999904 -9.632111e-05
1281        559         =          1.171082  1.579285e-01
1282        560         \          1.025465  2.514648e-02
1283        561      frac        686.255495  6.531250e+00  <<<SPIKE<<<
1284        562         {          0.990826 -9.216309e-03
1285        563         1          1.460686  3.789062e-01
1286        564        }{          1.001437  1.436234e-03
1287        565         2          0.999020 -9.803772e-04
1288        566         }          0.999972 -2.801418e-05
1289        567         \          1.001267  1.266479e-03
1290        568     times          0.702558 -3.530273e-01
1291        569         \          1.008212  8.178711e-03
1292        570      text          0.999860 -1.401901e-04
1293        571         {          1.000029  2.920628e-05
1294        572      Area          1.000407  4.072189e-04
1295        573        of          0.999850 -1.500845e-04

Spike 7: example_id=2, token_idx=191, abs_log_ratio=6.430

      token_idx    token_str  ratio_pA_over_pB  log_ratio         mark
1561        179            (          0.881205  -0.126465
1562        180            x          0.818271  -0.200562
1563        181            ^          1.410226   0.343750
1564        182            1          0.519807  -0.654297
1565        183            +          0.999153  -0.000847
1566        184            x          0.998414  -0.001587
1567        185            ^          0.992289  -0.007740
1568        186            2          0.982486  -0.017670
1569        187            +          0.997874  -0.002128
1570        188            x          0.999024  -0.000977
1571        189            ^          0.999907  -0.000093
1572        190            3          0.999187  -0.000813
1573        191           )^        619.980174   6.429688  <<<SPIKE<<<
1574        192            3          7.789171   2.052734
1575        193            \          0.673338  -0.395508
1576        194          ]\n          4.001698   1.386719
1577        195        where          1.755055   0.562500
1578        196           \(          1.438040   0.363281
1579        197            x          1.022403   0.022156
1580        198           \)          3.545308   1.265625
1581        199   represents          0.490465  -0.712402
1582        200          the          0.946781  -0.054688
1583        201       choice          9.195829   2.218750
1584        202           of          0.966398  -0.034180
1585        203    chocolate        373.110641   5.921875

Spike 8: example_id=1, token_idx=41, abs_log_ratio=6.297

     token_idx  token_str  ratio_pA_over_pB  log_ratio         mark
751         29   triangle          0.999978  -0.000022
752         30        ABC          0.999893  -0.000107
753         31          \          1.074678   0.072021
754         32     ).\n\n          0.973027  -0.027344
755         33      First          0.889636  -0.116943
756         34          ,          0.989466  -0.010590
757         35       note         11.993622   2.484375
758         36       that          3.104375   1.132812
759         37      since         13.804574   2.625000
760         38         \(          0.999756  -0.000244
761         39          D          0.737354  -0.304688
762         40         \)          0.985098  -0.015015
763         41    divides        542.872779   6.296875  <<<SPIKE<<<
764         42         \(          1.564030   0.447266
765         43         AB          0.998643  -0.001358
766         44         \)          1.000138   0.000138
767         45       into          1.000000   0.000000
768         46   segments          1.323492   0.280273
769         47         \(          0.976239  -0.024048
770         48         AD          0.999655  -0.000345
771         49         \)          8.099456   2.091797
772         50        and          0.999950  -0.000050
773         51         \(          0.999967  -0.000033
774         52         DB          2.020056   0.703125
775         53         \)          1.717751   0.541016

Spike 9: example_id=0, token_idx=501, abs_log_ratio=6.117

     token_idx     token_str  ratio_pA_over_pB  log_ratio         mark
489        489       applies          1.009813   0.009766
490        490         .\n\n          1.912550   0.648437
491        491           The          1.789670   0.582031
492        492          only          0.803523  -0.218750
493        493   restriction        141.616826   4.953125
494        494            on          2.893596   1.062500
495        495            \(          0.992581  -0.007446
496        496             m          3.068208   1.121094
497        497            \)          0.999841  -0.000159
498        498            is          0.989104  -0.010956
499        499          that          0.995372  -0.004639
500        500            \(          0.715541  -0.334717
501        501             m        453.587185   6.117188  <<<SPIKE<<<
502        502            \)          1.475020   0.388672
503        503        cannot        139.421260   4.937500
504        504            be          0.994643  -0.005371
505        505                        1.366838   0.312500
506        506             1          0.617588  -0.481934
507        507             (          2.553589   0.937500
508        508         since          1.031743   0.031250
509        509          then          1.988737   0.687500
510        510            \(          0.987037  -0.013048
511        511             b          0.998731  -0.001270
512        512             =          0.812399  -0.207764
513        513                        0.999911  -0.000089

Spike 10: example_id=2, token_idx=203, abs_log_ratio=5.922

      token_idx    token_str  ratio_pA_over_pB  log_ratio         mark
1573        191           )^        619.980174   6.429688
1574        192            3          7.789171   2.052734
1575        193            \          0.673338  -0.395508
1576        194          ]\n          4.001698   1.386719
1577        195        where          1.755055   0.562500
1578        196           \(          1.438040   0.363281
1579        197            x          1.022403   0.022156
1580        198           \)          3.545308   1.265625
1581        199   represents          0.490465  -0.712402
1582        200          the          0.946781  -0.054688
1583        201       choice          9.195829   2.218750
1584        202           of          0.966398  -0.034180
1585        203    chocolate        373.110641   5.921875  <<<SPIKE<<<
1586        204            ,          0.854719  -0.156982
1587        205           \(          1.150993   0.140625
1588        206            x          1.417648   0.348999
1589        207            ^          1.022294   0.022049
1590        208            2          0.979298  -0.020920
1591        209           \)          1.000071   0.000071
1592        210   represents          0.993915  -0.006104
1593        211          the          1.070227   0.067871
1594        212       choice          1.000020   0.000020
1595        213           of          1.000008   0.000008
1596        214      vanilla          0.998969  -0.001032
1597        215            ,          1.011440   0.011375

Spike 11: example_id=2, token_idx=566, abs_log_ratio=5.559

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1936        554           0          0.997645 -2.357483e-03
1937        555           =          1.000104  1.039505e-04
1938        556                      0.999998 -2.026558e-06
1939        557           2          0.999801 -1.986027e-04
1940        558           5          1.000008  8.463860e-06
1941        559           \          0.999888 -1.116991e-04
1942        560       ]\n\n          0.994759 -5.254745e-03
1943        561     Finally       1277.095643  7.152344e+00
1944        562           ,          1.000000 -3.576279e-07
1945        563          we          0.944977 -5.659485e-02
1946        564        need          0.977700 -2.255249e-02
1947        565          to          0.932733 -6.963634e-02
1948        566        find        259.521069  5.558838e+00  <<<SPIKE<<<
1949        567         the          1.005938  5.920410e-03
1950        568   remainder      57721.148256  1.096338e+01
1951        569        when          0.972077 -2.832031e-02
1952        570                      1.920036  6.523438e-01
1953        571           2          1.000093  9.286404e-05
1954        572           5          0.999997 -3.218651e-06
1955        573          is          0.999968 -3.242493e-05
1956        574     divided          0.999998 -2.384186e-06
1957        575          by          1.000000  0.000000e+00
1958        576                      0.999981 -1.871586e-05
1959        577           1          0.999996 -4.053116e-06
1960        578           0          1.000057  5.674362e-05

Spike 12: example_id=1, token_idx=242, abs_log_ratio=5.500

     token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
952        230          \(          0.999458 -5.419254e-04
953        231           F          0.999351 -6.489754e-04
954        232           \          0.667120 -4.047852e-01
955        233          ),          0.999773 -2.269745e-04
956        234       point          9.637146  2.265625e+00
957        235          \(          0.999985 -1.466274e-05
958        236           M          0.841224 -1.728973e-01
959        237          \)          0.999867 -1.325607e-04
960        238        lies          0.946781 -5.468750e-02
961        239          on          1.006122  6.103516e-03
962        240        line          1.701057  5.312500e-01
963        241          \(          0.927902 -7.482910e-02
964        242          EF        244.691932  5.500000e+00  <<<SPIKE<<<
965        243          \)          0.920232 -8.312988e-02
966        244        such          0.384031 -9.570312e-01
967        245        that          1.000000 -1.192093e-07
968        246          \(          0.970617 -2.982330e-02
969        247          DM          1.489496  3.984375e-01
970        248           =          0.573271 -5.563965e-01
971        249          DF          1.908818  6.464844e-01
972        250           \          1.536777  4.296875e-01
973        251          ).          0.989195 -1.086426e-02
974        252   Similarly          1.305520  2.666016e-01
975        253           ,          0.999990 -9.536743e-06
976        254       since          0.994158 -5.859375e-03

Spike 13: example_id=0, token_idx=132, abs_log_ratio=5.453

     token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
120        120          is          1.183477  1.684570e-01
121        121           a          0.999809 -1.913309e-04
122        122     divisor          0.999983 -1.657009e-05
123        123          of          0.999999 -7.152557e-07
124        124          \(          0.999995 -4.887581e-06
125        125           9          0.999997 -2.622604e-06
126        126           7          0.999775 -2.250671e-04
127        127          _b          0.999998 -1.788139e-06
128        128           \          1.000061  6.103516e-05
129        129          ).          2.110807  7.470703e-01
130        130   Therefore          1.261652  2.324219e-01
131        131           ,          0.999987 -1.263618e-05
132        132       there        233.486673  5.453125e+00  <<<SPIKE<<<
133        133      exists          0.978745 -2.148437e-02
134        134          an          0.987747 -1.232910e-02
135        135     integer          1.000000 -2.384186e-07
136        136          \(          0.999897 -1.034737e-04
137        137           k          0.990361 -9.685516e-03
138        138          \)          0.999949 -5.137920e-05
139        139        such          0.999982 -1.811981e-05
140        140        that          1.000000  0.000000e+00
141        141         :\n          0.999858 -1.416206e-04
142        142           \          1.000000  0.000000e+00
143        143         [\n          1.000000 -1.192093e-07
144        144           9          0.847232 -1.657810e-01

Spike 14: example_id=2, token_idx=168, abs_log_ratio=5.086

      token_idx    token_str  ratio_pA_over_pB  log_ratio         mark
1538        156    solutions          0.698113  -0.359375
1539        157            .          1.760204   0.565430
1540        158          The          2.538051   0.931396
1541        159   generating          1.058308   0.056671
1542        160     function          1.004343   0.004333
1543        161          for          1.004797   0.004786
1544        162          the          0.830650  -0.185547
1545        163       number          1.261960   0.232666
1546        164           of          0.999546  -0.000454
1547        165         ways          0.650395  -0.430176
1548        166           to          0.998593  -0.001408
1549        167       choose          2.650132   0.974609
1550        168    chocolate        161.731491   5.085938  <<<SPIKE<<<
1551        169            ,          0.891157  -0.115234
1552        170      vanilla          0.999431  -0.000569
1553        171            ,          0.999997  -0.000003
1554        172          and          1.033350   0.032806
1555        173   strawberry          0.999979  -0.000021
1556        174           is          8.275350   2.113281
1557        175        given          0.671368  -0.398437
1558        176           by          0.999890  -0.000110
1559        177          :\n          1.221641   0.200195
1560        178           \[          1.040566   0.039764
1561        179            (          0.881205  -0.126465
1562        180            x          0.818271  -0.200562

Spike 15: example_id=0, token_idx=493, abs_log_ratio=4.953

     token_idx     token_str  ratio_pA_over_pB  log_ratio         mark
481        481         equal          1.000028   0.000028
482        482            to          0.999996  -0.000004
483        483                        0.910436  -0.093832
484        484             4          0.697793  -0.359833
485        485             ,          0.914074  -0.089844
486        486           the          2.415330   0.881836
487        487          same          1.810766   0.593750
488        488         logic          0.795714  -0.228516
489        489       applies          1.009813   0.009766
490        490         .\n\n          1.912550   0.648437
491        491           The          1.789670   0.582031
492        492          only          0.803523  -0.218750
493        493   restriction        141.616826   4.953125  <<<SPIKE<<<
494        494            on          2.893596   1.062500
495        495            \(          0.992581  -0.007446
496        496             m          3.068208   1.121094
497        497            \)          0.999841  -0.000159
498        498            is          0.989104  -0.010956
499        499          that          0.995372  -0.004639
500        500            \(          0.715541  -0.334717
501        501             m        453.587185   6.117188
502        502            \)          1.475020   0.388672
503        503        cannot        139.421260   4.937500
504        504            be          0.994643  -0.005371
505        505                        1.366838   0.312500

Spike 16: example_id=0, token_idx=503, abs_log_ratio=4.938

     token_idx     token_str  ratio_pA_over_pB  log_ratio         mark
491        491           The          1.789670   0.582031
492        492          only          0.803523  -0.218750
493        493   restriction        141.616826   4.953125
494        494            on          2.893596   1.062500
495        495            \(          0.992581  -0.007446
496        496             m          3.068208   1.121094
497        497            \)          0.999841  -0.000159
498        498            is          0.989104  -0.010956
499        499          that          0.995372  -0.004639
500        500            \(          0.715541  -0.334717
501        501             m        453.587185   6.117188
502        502            \)          1.475020   0.388672
503        503        cannot        139.421260   4.937500  <<<SPIKE<<<
504        504            be          0.994643  -0.005371
505        505                        1.366838   0.312500
506        506             1          0.617588  -0.481934
507        507             (          2.553589   0.937500
508        508         since          1.031743   0.031250
509        509          then          1.988737   0.687500
510        510            \(          0.987037  -0.013048
511        511             b          0.998731  -0.001270
512        512             =          0.812399  -0.207764
513        513                        0.999911  -0.000089
514        514             7          1.319620   0.277344
515        515            \)          1.755055   0.562500

Spike 17: example_id=0, token_idx=192, abs_log_ratio=4.750

     token_idx token_str  ratio_pA_over_pB     log_ratio         mark
180        180         k          0.999955 -4.482269e-05
181        181         \          0.918885 -8.459473e-02
182        182      impl          1.000424  4.234314e-04
183        183       ies          1.000000 -3.576279e-07
184        184         (          2.361684  8.593750e-01
185        185         9          0.997906 -2.096653e-03
186        186         -          0.999558 -4.425049e-04
187        187         k          0.999858 -1.420975e-04
188        188        )b          0.999685 -3.154278e-04
189        189         =          0.988478 -1.158905e-02
190        190                    0.998369 -1.632094e-03
191        191         7          0.999954 -4.553795e-05
192        192        (k        115.584285  4.750000e+00  <<<SPIKE<<<
193        193         -          0.999997 -3.337860e-06
194        194                    0.999972 -2.789497e-05
195        195         1          0.999903 -9.667873e-05
196        196       )\n          1.126666  1.192627e-01
197        197         \          1.000001  9.536743e-07
198        198       ]\n          1.000011  1.096725e-05
199        199      This          1.573221  4.531250e-01
200        200   implies          0.910510 -9.375000e-02
201        201      that          3.770277  1.327148e+00
202        202        \(          2.221307  7.980957e-01
203        203         b          0.605939 -5.009766e-01
204        204        \)          1.623953  4.848633e-01

Spike 18: example_id=1, token_idx=311, abs_log_ratio=4.664

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1021        299          \(          0.999802 -1.983643e-04
1022        300          AF          0.999988 -1.204014e-05
1023        301          NB          1.000005  5.245209e-06
1024        302          CE          1.000027  2.729893e-05
1025        303           M          0.999985 -1.513958e-05
1026        304          \)          0.999983 -1.692772e-05
1027        305         can          0.965455 -3.515625e-02
1028        306          be          0.999995 -5.125999e-06
1029        307     divided          2.538671  9.316406e-01
1030        308        into          0.999847 -1.525879e-04
1031        309         two         37.232703  3.617188e+00
1032        310   triangles          1.015748  1.562500e-02
1033        311           :        106.066102  4.664062e+00  <<<SPIKE<<<
1034        312           \          0.850244 -1.622314e-01
1035        313          (\          1.000000 -2.384186e-07
1036        314    triangle          0.999922 -7.772446e-05
1037        315           A          0.627007 -4.667969e-01
1038        316          FE          0.692680 -3.671875e-01
1039        317          \)          0.994317 -5.699158e-03
1040        318         and          0.998491 -1.509666e-03
1041        319           \          0.960459 -4.034424e-02
1042        320          (\          0.999998 -1.907349e-06
1043        321    triangle          0.999938 -6.246567e-05
1044        322           B          2.436652  8.906250e-01
1045        323          EM         34.704696  3.546875e+00

Spike 19: example_id=0, token_idx=289, abs_log_ratio=4.531

     token_idx token_str  ratio_pA_over_pB  log_ratio         mark
277        277         b          0.999651  -0.000349
278        278        \)          0.999886  -0.000114
279        279        is          0.918885  -0.084595
280        280        \(          0.662252  -0.412109
281        281         2         73.469841   4.296875
282        282         8          6.125743   1.812500
283        283         \          1.803707   0.589844
284        284        ).          0.969707  -0.030762
285        285        We          0.550368  -0.597168
286        286       now          1.056210   0.054687
287        287     check          0.499894  -0.693359
288        288        if          0.895519  -0.110352
289        289       any         92.874582   4.531250  <<<SPIKE<<<
290        290     other          1.737150   0.552246
291        291    values          0.932102  -0.070312
292        292        of          1.050937   0.049683
293        293        \(          1.000019   0.000019
294        294         b          1.000840   0.000839
295        295        \)          0.841827  -0.172180
296        296   greater          5.811075   1.759766
297        297      than          0.999999  -0.000001
298        298                    0.992218  -0.007812
299        299         9          2.991285   1.095703
300        300   satisfy         10.584334   2.359375
301        301       the          0.986662  -0.013428

Spike 20: example_id=0, token_idx=281, abs_log_ratio=4.297

     token_idx  token_str  ratio_pA_over_pB     log_ratio         mark
269        269          \          1.034265  3.369141e-02
270        270         ),          1.000000 -2.384186e-07
271        271        the          1.312071  2.716064e-01
272        272   smallest          8.982808  2.195312e+00
273        273   possible          0.743863 -2.958984e-01
274        274      value          1.017982  1.782227e-02
275        275        for          1.013580  1.348877e-02
276        276         \(          0.999788 -2.118349e-04
277        277          b          0.999651 -3.490448e-04
278        278         \)          0.999886 -1.138449e-04
279        279         is          0.918885 -8.459473e-02
280        280         \(          0.662252 -4.121094e-01
281        281          2         73.469841  4.296875e+00  <<<SPIKE<<<
282        282          8          6.125743  1.812500e+00
283        283          \          1.803707  5.898438e-01
284        284         ).          0.969707 -3.076172e-02
285        285         We          0.550368 -5.971680e-01
286        286        now          1.056210  5.468750e-02
287        287      check          0.499894 -6.933594e-01
288        288         if          0.895519 -1.103516e-01
289        289        any         92.874582  4.531250e+00
290        290      other          1.737150  5.522461e-01
291        291     values          0.932102 -7.031250e-02
292        292         of          1.050937  4.968262e-02
293        293         \(          1.000019  1.859665e-05

Spike 21: example_id=0, token_idx=380, abs_log_ratio=4.250

     token_idx   token_str  ratio_pA_over_pB  log_ratio         mark
368        368         ]\n          0.999904  -0.000096
369        369          So          0.855345  -0.156250
370        370           ,          0.943781  -0.057861
371        371          \(          1.001527   0.001526
372        372           b          2.465375   0.902344
373        373           =          1.000855   0.000854
374        374                      0.999999  -0.000001
375        375           2          0.999682  -0.000319
376        376           8          0.999960  -0.000040
377        377          \)          1.000571   0.000571
378        378       works          0.547955  -0.601562
379        379           .          1.015500   0.015381
380        380   Similarly         70.105412   4.250000  <<<SPIKE<<<
381        381           ,          1.000095   0.000095
382        382         for          0.832274  -0.183594
383        383          \(          0.673215  -0.395691
384        384           b          0.999436  -0.000564
385        385           =          0.999026  -0.000975
386        386                      0.998790  -0.001211
387        387           4          3.657848   1.296875
388        388           2          1.582466   0.458984
389        389           \          0.959814  -0.041016
390        390        ):\n          0.999222  -0.000778
391        391           \          0.999993  -0.000007
392        392         [\n          1.000010   0.000010

Spike 22: example_id=1, token_idx=400, abs_log_ratio=4.062

      token_idx      token_str  ratio_pA_over_pB  log_ratio         mark
1110        388              B          3.497167   1.251953
1111        389             \)          0.976120  -0.024170
1112        390        through          1.195675   0.178711
1113        391             \(          1.096945   0.092529
1114        392              F          0.753367  -0.283203
1115        393             \)          0.630384  -0.461426
1116        394            and          0.993335  -0.006687
1117        395             \(          1.000305   0.000305
1118        396              E          0.977789  -0.022461
1119        397              \          1.068661   0.066406
1120        398             ),          0.798828  -0.224609
1121        399   respectively          2.222934   0.798828
1122        400            .\n         58.119428   4.062500  <<<SPIKE<<<
1123        401          Since          0.418494  -0.871094
1124        402             \(          1.060344   0.058594
1125        403              F          1.810766   0.593750
1126        404             \)          0.999298  -0.000702
1127        405            and          1.056210   0.054687
1128        406             \(          0.999965  -0.000035
1129        407              E          1.146506   0.136719
1130        408             \)          0.999975  -0.000025
1131        409            are          1.027219   0.026855
1132        410    reflections          3.686537   1.304688
1133        411             of          2.655313   0.976563
1134        412             \(          1.005386   0.005371

Spike 23: example_id=0, token_idx=599, abs_log_ratio=4.062

     token_idx  token_str  ratio_pA_over_pB  log_ratio         mark
587        587        not          1.000004   0.000004
588        588    specify          0.993672  -0.006348
589        589         an          1.269066   0.238281
590        590      upper          0.994059  -0.005959
591        591      limit          0.791838  -0.233398
592        592          ,          0.923636  -0.079437
593        593         we          0.923946  -0.079102
594        594     assume          0.803523  -0.218750
595        595        the          1.041868   0.041016
596        596   question          2.361684   0.859375
597        597    intends         12.182494   2.500000
598        598         to          2.826566   1.039062
599        599    include         58.119428   4.062500  <<<SPIKE<<<
600        600        all          2.020056   0.703125
601        601      valid          0.435164  -0.832031
602        602         \(          0.923044  -0.080078
603        603          b          0.991428  -0.008609
604        604         \)          2.255737   0.813477
605        605   starting          9.712731   2.273438
606        606       from          0.999790  -0.000210
607        607                     1.038821   0.038086
608        608          2          0.966319  -0.034262
609        609          8          0.997142  -0.002862
610        610      .\n\n          0.574252  -0.554688
611        611       Thus          0.923044  -0.080078

Spike 24: example_id=1, token_idx=375, abs_log_ratio=3.967

      token_idx     token_str  ratio_pA_over_pB  log_ratio         mark
1085        363             -          0.999990  -0.000010
1086        364            \(          0.978267  -0.021973
1087        365            AE          1.454991   0.375000
1088        366             =          0.984493  -0.015628
1089        367                        0.866485  -0.143311
1090        368             2          0.954148  -0.046936
1091        369             0          0.977506  -0.022751
1092        370             \          0.943781  -0.057861
1093        371           )\n          0.936665  -0.065430
1094        372             -          0.887195  -0.119690
1095        373            \(          3.190432   1.160156
1096        374            EF          0.800390  -0.222656
1097        375            \)         52.815086   3.966797  <<<SPIKE<<<
1098        376            is          1.648721   0.500000
1099        377           the          1.169118   0.156250
1100        378      distance          1.741397   0.554688
1101        379       between          1.243305   0.217773
1102        380           the          2.175685   0.777344
1103        381   reflections          3.285284   1.189453
1104        382            of          1.938878   0.662109
1105        383            \(          0.993915  -0.006104
1106        384             A         31.598985   3.453125
1107        385            \)          1.000824   0.000824
1108        386           and          1.592154   0.465088
1109        387            \(          0.999863  -0.000137

Spike 25: example_id=0, token_idx=238, abs_log_ratio=3.938

     token_idx  token_str  ratio_pA_over_pB  log_ratio         mark
226        226                     0.999999  -0.000001
227        227          1          0.999998  -0.000002
228        228         )\          0.998565  -0.001436
229        229          )          2.475024   0.906250
230        230        and          1.060344   0.058594
231        231      since          0.754840  -0.281250
232        232         \(          0.811705  -0.208618
233        233          9          1.775743   0.574219
234        234          -          0.983776  -0.016357
235        235          k          0.998717  -0.001284
236        236         \)          0.872535  -0.136353
237        237         is          2.655313   0.976563
238        238     always         51.290215   3.937500  <<<SPIKE<<<
239        239   positive         24.802328   3.210938
240        240       when          3.032463   1.109375
241        241         \(          0.999019  -0.000981
242        242          k          0.962748  -0.037964
243        243          <          2.681371   0.986328
244        244                     0.999597  -0.000403
245        245          9          0.987298  -0.012783
246        246          \          1.142315   0.133057
247        247         ),          0.987754  -0.012321
248        248         it         12.667789   2.539062
249        249    follows          0.309786  -1.171875
250        250       that          0.999481  -0.000519

Spike 26: example_id=2, token_idx=137, abs_log_ratio=3.902

      token_idx    token_str  ratio_pA_over_pB  log_ratio         mark
1507        125            v          0.999720  -0.000280
1508        126            +          0.999953  -0.000047
1509        127            s          0.999988  -0.000012
1510        128            =          0.999880  -0.000120
1511        129                       0.999991  -0.000009
1512        130            9          0.999985  -0.000015
1513        131            \          0.967814  -0.032715
1514        132          ]\n          0.999242  -0.000758
1515        133           \[          0.989081  -0.010979
1516        134            c          0.977133  -0.023132
1517        135            >          0.915023  -0.088806
1518        136            v          0.998064  -0.001938
1519        137            \         49.518372   3.902344  <<<SPIKE<<<
1520        138          ]\n          1.012436   0.012360
1521        139           \[          0.999970  -0.000030
1522        140            v          0.998308  -0.001693
1523        141            >          0.999948  -0.000052
1524        142            s          0.999989  -0.000011
1525        143            \          0.999970  -0.000030
1526        144        ]\n\n          2.125286   0.753906
1527        145           We          3.304590   1.195312
1528        146         will          1.707715   0.535156
1529        147          use          1.512952   0.414062
1530        148   generating          0.868815  -0.140625
1531        149    functions          0.999104  -0.000897

Spike 27: example_id=2, token_idx=17, abs_log_ratio=3.812

      token_idx    token_str  ratio_pA_over_pB     log_ratio         mark
1387          5            ,          0.999964 -3.623962e-05
1388          6           we          0.973621 -2.673340e-02
1389          7         need          0.903425 -1.015625e-01
1390          8           to          0.999974 -2.646446e-05
1391          9         find          1.160020  1.484375e-01
1392         10          the          0.985851 -1.424980e-02
1393         11       number          0.999354 -6.463528e-04
1394         12           of          0.999832 -1.678467e-04
1395         13         ways          0.792999 -2.319336e-01
1396         14           to          0.991917 -8.115768e-03
1397         15       assign          0.973977 -2.636719e-02
1398         16                      11.807678  2.468750e+00
1399         17            3         45.263456  3.812500e+00  <<<SPIKE<<<
1400         18        types         11.092287  2.406250e+00
1401         19           of          0.992539 -7.489204e-03
1402         20          ice          0.966914 -3.364563e-02
1403         21        cream          0.921468 -8.178711e-02
1404         22            (          1.323492  2.802734e-01
1405         23           ch          0.996865 -3.139496e-03
1406         24      ocolate          0.999969 -3.135204e-05
1407         25            ,          0.999476 -5.245209e-04
1408         26      vanilla          0.999746 -2.536774e-04
1409         27            ,          0.999996 -3.695488e-06
1410         28          and          0.824991 -1.923828e-01
1411         29   strawberry          1.000000  4.768372e-07

Spike 28: example_id=0, token_idx=523, abs_log_ratio=3.736

     token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
511        511           b          0.998731 -1.270294e-03
512        512           =          0.812399 -2.077637e-01
513        513                      0.999911 -8.869171e-05
514        514           7          1.319620  2.773438e-01
515        515          \)          1.755055  5.625000e-01
516        516       would         19.774140  2.984375e+00
517        517         not          0.894208 -1.118164e-01
518        518          be          1.175989  1.621094e-01
519        519     greater          0.975852 -2.444458e-02
520        520        than          0.999990 -1.025200e-05
521        521                      0.998611 -1.389861e-03
522        522           9          0.995027 -4.984975e-03
523        523          ).         41.943695  3.736328e+00  <<<SPIKE<<<
524        524   Therefore          1.310630  2.705078e-01
525        525           ,          1.000000 -1.192093e-07
526        526          \(          3.253357  1.179688e+00
527        527           m          1.034897  3.430176e-02
528        528          \)          1.057468  5.587769e-02
529        529         can          1.077963  7.507324e-02
530        530        take         27.028044  3.296875e+00
531        531         any          1.629513  4.882812e-01
532        532     integer          0.983295 -1.684570e-02
533        533       value          0.930397 -7.214355e-02
534        534        from          1.634294  4.912109e-01
535        535                      0.999460 -5.400181e-04

Spike 29: example_id=1, token_idx=309, abs_log_ratio=3.617

      token_idx   token_str  ratio_pA_over_pB     log_ratio         mark
1019        297          pt          0.999972 -2.825260e-05
1020        298        agon          0.999885 -1.152754e-04
1021        299          \(          0.999802 -1.983643e-04
1022        300          AF          0.999988 -1.204014e-05
1023        301          NB          1.000005  5.245209e-06
1024        302          CE          1.000027  2.729893e-05
1025        303           M          0.999985 -1.513958e-05
1026        304          \)          0.999983 -1.692772e-05
1027        305         can          0.965455 -3.515625e-02
1028        306          be          0.999995 -5.125999e-06
1029        307     divided          2.538671  9.316406e-01
1030        308        into          0.999847 -1.525879e-04
1031        309         two         37.232703  3.617188e+00  <<<SPIKE<<<
1032        310   triangles          1.015748  1.562500e-02
1033        311           :        106.066102  4.664062e+00
1034        312           \          0.850244 -1.622314e-01
1035        313          (\          1.000000 -2.384186e-07
1036        314    triangle          0.999922 -7.772446e-05
1037        315           A          0.627007 -4.667969e-01
1038        316          FE          0.692680 -3.671875e-01
1039        317          \)          0.994317 -5.699158e-03
1040        318         and          0.998491 -1.509666e-03
1041        319           \          0.960459 -4.034424e-02
1042        320          (\          0.999998 -1.907349e-06
1043        321    triangle          0.999938 -6.246567e-05

In [6]:
with pd.ExcelWriter("spike_tables.xlsx") as writer:
    df.to_excel(writer, sheet_name="full_df", index=False)
    top.to_excel(writer, sheet_name="top_spikes", index=False)
    for i in range(30):
        row = top.iloc[i]
        out = show_spike_context(df, row.example_id, row.token_idx, window=12)
        out.to_excel(writer, sheet_name=f"spike_{i}", index=False)

In [7]:
def text_snippet_around_spike(df, example_id, seed, token_idx, char_window=160):
    g = df[(df.example_id==example_id) & (df.seed==seed)].sort_values("token_idx")
    tokens = g["token_str"].astype(str).tolist()
    
    # Reconstruct progressively (token_str often includes leading spaces; that's fine)
    prefix = "".join(tokens[:token_idx])
    spike_tok = tokens[token_idx] if token_idx < len(tokens) else ""
    suffix = "".join(tokens[token_idx+1:])
    
    # Build marked text
    text = prefix + "[[[" + spike_tok + "]]]" + suffix
    
    # Slice around marker
    m = text.find("[[[")
    start = max(0, m - char_window)
    end = min(len(text), m + char_window)
    return text[start:end]

row = top.iloc[0]
print(text_snippet_around_spike(df, row.example_id, row.seed, row.token_idx))

tions (where at least one variable is zero) is:
\[ 3 \times 10 = 30 \]

Thus, the number of valid solutions is:
\[ 55 - 30 = 25 \]

Finally, we need to find the[[[ remainder]]] when 25 is divided by 1000:
\[ 25 \mod 1000 = 25 \]

Therefore, the remainder when \(N\) is divided by 1000 is:
\[
\boxed{25}
\]

## Top 5% Spikes by type

In [27]:
import re

def token_type(tok: str) -> str:
    t = tok.strip()

    if t == "":
        return "whitespace"

    # LaTeX-style math control tokens: \(, \), \[, \], \frac, ...
    if t.startswith("\\"):
        return "math_control"

    # Pure digits
    if re.fullmatch(r"[0-9]+", t):
        return "number"

    # Symbols and punctuation (no letters or digits)
    if re.fullmatch(r"[^\w\s]+", t):
        return "symbol"

    # Alphabetic words
    if re.fullmatch(r"[A-Za-z]+", t):
        return "word"

    # Mixed leftovers (ex: k_1, m9)
    return "other"

In [28]:
# 1) sort + compute token_type + abs_log_ratio (if not already)
df = df.sort_values(["example_id", "token_idx"]).copy()
df["token_type"] = df["token_str"].apply(token_type)
df["abs_log_ratio"] = df["log_ratio"].abs()

# 2) compute previous token type ON FULL DF
df["prev_token_type"] = df.groupby("example_id")["token_type"].shift(1)

# 3) now define spikes (top 5% example)
q = df["abs_log_ratio"].quantile(0.95)
spikes = df[df["abs_log_ratio"] >= q].copy()

# 4) now this works
spikes.groupby(["token_type", "prev_token_type"]).size().sort_values(ascending=False)

token_type    prev_token_type
word          word               44
              symbol             17
              math_control       15
math_control  word                4
symbol        word                4
word          number              3
math_control  symbol              2
number        number              2
              whitespace          2
symbol        number              2
math_control  number              1
number        math_control        1
              symbol              1
other         number              1
symbol        math_control        1
whitespace    word                1
dtype: int64

In [29]:
(
    spikes
    .assign(
        structural_prev=lambda x: x["prev_token_type"].isin(
            ["symbol", "math_control", "number"]
        )
    )
    .groupby(["token_type", "structural_prev"])
    .size()
)

token_type    structural_prev
math_control  False               4
              True                3
number        False               2
              True                4
other         True                1
symbol        False               4
              True                3
whitespace    False               1
word          False              44
              True               35
dtype: int64